# Generated by Django 5.2.5 on 2025-09-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='discussion',
        ),
        migrations.RenameField(
            model_name='groupdiscussion',
            old_name='author',
            new_name='creator',
        ),
        migrations.RemoveField(
            model_name='groupdiscussion',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='members',
        ),
    ]
