# Generated by Django 5.2.5 on 2025-09-06 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_groupdiscussion_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdiscussion',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='groups.studygroup'),
        ),
    ]
