# Generated by Django 5.2.5 on 2025-09-07 05:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_studygroup_members_groupinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
