# Generated by Django 5.2.5 on 2025-09-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='nopfp.jpg', upload_to='pfp'),
        ),
    ]
