# Generated by Django 5.2.5 on 2025-09-06 05:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
        ('users', '0003_customuser_friends_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friend_of', through='social.Friendship', to=settings.AUTH_USER_MODEL),
        ),
    ]
